CREATE TABLE [dbo].[Apothecary]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	MonthlySalary MONEY NOT NULL CHECK (MonthlySalary > 0),
	IsEmployed BIT NOT NULL DEFAULT 1,
	HireDate DATE NOT NULL DEFAULT GETDATE(),
	FireDate DATE CHECK(HireDate <= FireDate)
)
