CREATE TABLE [dbo].[Doctor]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	HasValidMedicalLicense BIT NOT NULL DEFAULT 1,
	RowVersion INT NOT NULL DEFAULT 1
)
