CREATE TABLE [dbo].[Medicine]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	UnitPrice MONEY NOT NULL, 
    Amount INT NOT NULL, 
    MedicineTypeId INT NOT NULL,
	Refund DECIMAL(3,2),
	MedType NVARCHAR(20) NOT NULL,
    Unit NVARCHAR(10) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Expired BIT NOT NULL DEFAULT(1)

	CHECK (MedType IN ('SALVE','PILL','SYRUP','SPRAY', 'SOLUTION', 'LIQUID')),
	CHECK (Unit IN ('PCS','GRAMS','MILILITERS'))
)
