//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApothecaryShift
    {
        public int Id { get; set; }
        public int ApothecaryId { get; set; }
        public System.DateTime ShiftStart { get; set; }
        public Nullable<System.DateTime> ShiftEnd { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
        public Nullable<int> ServedClientsCount { get; set; }
    
        public virtual Apothecary Apothecary { get; set; }
    }
}
