//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedPrescription
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public int ApothecaryId { get; set; }
        public System.DateTime CompletionDate { get; set; }
    
        public virtual Apothecary Apothecary { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
