//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class iDrugsEntities : DbContext
    {
        public iDrugsEntities()
            : base("name=iDrugsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DrugStoreAvailableMedicine> DrugStoreAvailableMedicines { get; set; }
        public virtual DbSet<MedicineWarehouse> MedicineWarehouses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Apothecary> Apothecaries { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<PrescriptionItem> PrescriptionItems { get; set; }
    
        public virtual int InsertApothecary(string firstName, string lastName, Nullable<decimal> monthlySalary)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var monthlySalaryParameter = monthlySalary.HasValue ?
                new ObjectParameter("MonthlySalary", monthlySalary) :
                new ObjectParameter("MonthlySalary", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertApothecary", firstNameParameter, lastNameParameter, monthlySalaryParameter);
        }
    
        public virtual int FireApothecary(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FireApothecary", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CreateOrder(Nullable<int> apothecaryId)
        {
            var apothecaryIdParameter = apothecaryId.HasValue ?
                new ObjectParameter("ApothecaryId", apothecaryId) :
                new ObjectParameter("ApothecaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CreateOrder", apothecaryIdParameter);
        }
    
        public virtual int DeleteMedicine(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMedicine", idParameter);
        }
    
        public virtual int DeleteOrder(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOrder", orderIdParameter);
        }
    
        public virtual int RemoveDoctorLicense(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveDoctorLicense", idParameter);
        }
    
        public virtual int AcceptCreatedPrescription(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AcceptCreatedPrescription", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AddPrescription(Nullable<int> doctorId, Nullable<int> apothecaryId, Nullable<System.DateTime> prescriptionDate, string email)
        {
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("doctorId", doctorId) :
                new ObjectParameter("doctorId", typeof(int));
    
            var apothecaryIdParameter = apothecaryId.HasValue ?
                new ObjectParameter("apothecaryId", apothecaryId) :
                new ObjectParameter("apothecaryId", typeof(int));
    
            var prescriptionDateParameter = prescriptionDate.HasValue ?
                new ObjectParameter("prescriptionDate", prescriptionDate) :
                new ObjectParameter("prescriptionDate", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AddPrescription", doctorIdParameter, apothecaryIdParameter, prescriptionDateParameter, emailParameter);
        }
    
        public virtual int AddPrescriptionItem(Nullable<int> medicineId, Nullable<int> prescriptionId, Nullable<int> quantityToBuy)
        {
            var medicineIdParameter = medicineId.HasValue ?
                new ObjectParameter("medicineId", medicineId) :
                new ObjectParameter("medicineId", typeof(int));
    
            var prescriptionIdParameter = prescriptionId.HasValue ?
                new ObjectParameter("prescriptionId", prescriptionId) :
                new ObjectParameter("prescriptionId", typeof(int));
    
            var quantityToBuyParameter = quantityToBuy.HasValue ?
                new ObjectParameter("quantityToBuy", quantityToBuy) :
                new ObjectParameter("quantityToBuy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPrescriptionItem", medicineIdParameter, prescriptionIdParameter, quantityToBuyParameter);
        }
    
        public virtual int ChangePrescriptedAmount(Nullable<int> id, Nullable<int> newAmount, Nullable<int> version)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var newAmountParameter = newAmount.HasValue ?
                new ObjectParameter("newAmount", newAmount) :
                new ObjectParameter("newAmount", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePrescriptedAmount", idParameter, newAmountParameter, versionParameter);
        }
    }
}
