//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.DrugStoreAvailableMedicines = new HashSet<DrugStoreAvailableMedicine>();
            this.MedicineWarehouses = new HashSet<MedicineWarehouse>();
            this.OrderItems = new HashSet<OrderItem>();
            this.PrescriptionItems = new HashSet<PrescriptionItem>();
        }
    
        public int Id { get; set; }
        public decimal UnitPrice { get; set; }
        public int Amount { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public string MedType { get; set; }
        public string Unit { get; set; }
        public string Name { get; set; }
        public bool Expired { get; set; }
        public int MedicineTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugStoreAvailableMedicine> DrugStoreAvailableMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineWarehouse> MedicineWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionItem> PrescriptionItems { get; set; }
    }
}
